services:
  server:
    build:
      context: .
      dockerfile: ./services/server/Dockerfile
      args:
        PORT: 81
    ports:
      - "81:81"
    restart: always
    env_file:
      - .env
  nginx:
    depends_on:
      - server
    build:
      context: .
      dockerfile: ./services/nginx/Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    restart: always
  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile
      args:
        BACKEND_URL: ${BACKEND_URL}
        S3_URL: ${BACKEND_URL}
    ports:
      - '3000:3000'
    restart: always